### ISSUE TITLE
Identity of the evaluators

### ISSUE THREAD

**Issue by caridy** [tc39/proposal-ses#20]
In the detailed proposal, the following step describes the creation of the evaluators:

> 1. `spawn` populates this `freshGlobal` with overriding
>        bindings for the evaluators that have global names (currently
>        only `eval` and `Function`). It binds each of these names to
>        fresh objects whose `[[Prototype]]`s are the corresponding
>        objects from the parent realm.

The second part of it is confusing. Why is the identity of the evaluators important? Specifically:

```
sharedRoot.eval('function foo(value) { console.log(value); }');
const childRealm = sharedRoot.spawn({});
Object.getPrototypeOf(childRealm.eval) === sharedRoot.eval; // yield *true*?
```

How is this important considering that both `eval` methods are doing the right thing?

**Comment by erights** [comment]
It is not actually important for the eval function. It may even be a bad idea.

However, it is nice for the Function constructor, though arguable. It is nice because it mirrors the new class-pattern where the subclass constructor inherits from the superclass constructor.

It is nice for the global object, as the per-lightweight-realm global inherits bindings from its parent global, except for the ones it overrides specifically.

In the polyfill examples, it is nice for Date for the same reason it is nice for Function. It is nice for Math for the same reason it is nice for the global object.

Given that we follow this pattern everywhere else, it is still arguable whether we should follow it for the eval function or not, since it really doesn't fall into any of these cases.

**Comment by caridy** [comment]
Actually, I made a mistake when asking the question. one thing is _theRealm_.eval and another thing is the _eval_ evaluator function added to the _freshGlobal_ to prevent code executed in the spawned realm to reach to the parent evaluator by doing `this.eval`.

But it seems that we are good, here are the details:

```
Object.getPrototypeOf(childRealm.eval) === sharedRoot.eval; // false
childRealm.global.eval === sharedRoot.global.eval; // false
Object.getPrototypeOf(childRealm.global.eval) === sharedRoot.eval; // false
```

Here is what I have so far:

![image](https://cloud.githubusercontent.com/assets/38969/14569423/b20ac4c8-030c-11e6-81af-2f2ce842867a.png)

which means `eval` is just a new function bound to the _freshGlobal_ and created when spawning, and its body guarantees that the string value is evaluated in the correct realm. while the Realm's `eval` is just part of the Realms API inheritance described in step 2 here:

![image](https://cloud.githubusercontent.com/assets/38969/14569539/6a93bd4c-030d-11e6-9f84-ffdd8a73c71f.png)

If I get all this correctly, then the following question is: do we need to prevent code evaluated in the spawned realm to reach out to the parent's eval? e.g.:

```
childRealm.eval('Object.getPropotypeOf(this).eval("function foo () {}")'); // defines foo in the parent realm global object
```

**Comment by erights** [comment]
> do we need to prevent code evaluated in the spawned realm to reach out to the parent's eval?

I do not believe so. First, I do not see a benefit. Second, given the rest of the proposal, such prevention would be difficult.

**Comment by caridy** [comment]
Ok. we can close this one now, we can revisit this if needed.
