### ISSUE TITLE
Actual specification

### ISSUE THREAD

**Issue by benjamingr** [tc39/proposal-ses#3]
It would be great if you could add the actual proposed changes to the ES spec here so they can be discussed in context.

**Comment by erights** [comment]
@benjamingr I agree but am not sure how to proceed. It fits into the spec in a different way than other specs we would have used as examples. Adding @bterlson , @allenwb .

How should we go about this? Where would we start?

**Comment by erights** [comment]
I think the first question is how to populate the proto-ses realm with all the contents of the main spec mandatory primordials, but in a transitively frozen state, by a blanket statement instead of repeating them all. This would be a statement like "except where stated otherwise..." Once we have spec text populating the bulk of the ses realm in this way, then I imagine it would be straightforward to state the few "otherwise" cases -- Date and Math.

With the existence of those to refer to, then the three elements of our API could be specified operationally in the normal manner. Does this sound like a good plan?

**Comment by allenwb** [comment]
@erights 
Why don't you use as a model the parts of Annex B that modify the semantics of material in the main body of the spec.  

For example, you could (indirectly) add a statement to [Clause 17](https://tc39.github.io/ecma262/#sec-ecmascript-standard-built-in-objects) that provides the SES variations

**Comment by caridy** [comment]
@benjamingr I will work on the basics to have the spec text in this repo as part of the proposal.

**Comment by bterlson** [comment]
Gah, coming a month late to say sorry I missed the ping above :(

**Comment by caridy** [comment]
Preliminary infrastructure for the spec text is now in place, more details here: https://github.com/FUDCo/frozen-realms#spec-text

Should we close this issue now and open other issues when specific spec details need to be discussed?

**Comment by erights** [comment]
@caridy 

> Should we close this issue now and open other issues when specific spec details need to be discussed?

Yes, thanks. This is a good idea. Closing.
